export const shortQuotes = [
  "Stay sharp.",
  "One step at a time.",
  "Knowledge is power.",
  "Keep moving forward.",
  "Focus and win.",
  "Dream. Plan. Do.",
  "Study today, shine tomorrow.",
  "Discipline beats motivation.",
  "Small steps, big results.",
  "Learn. Grow. Elevate.",
  "Consistency is key.",
  "Progress, not perfection.",
  "Every day counts.",
  "Mind over matter.",
  "Stay focused.",
  "Build your future.",
  "Smart work pays.",
  "Never stop learning.",
  "Push your limits.",
  "Elevate yourself.",
  "Stay curious.",
  "Learn daily.",
  "Time is gold.",
  "Grow every day.",
  "Be unstoppable.",
  "Focus brings results.",
  "Knowledge never fades.",
  "Start small, think big.",
  "Hard work wins.",
  "Sharpen your mind.",
  "Discipline equals freedom.",
  "Future starts now.",
  "Be better daily.",
  "Every minute counts.",
  "Learning never ends.",
  "Greatness is earned.",
  "Dream big, work hard.",
  "Stay hungry.",
  "Chase progress.",
  "Elevate your mind.",
  "No excuses.",
  "Think smarter.",
  "Build habits.",
  "Keep improving.",
  "Push forward.",
  "Master yourself.",
  "Success is practice.",
  "Stay disciplined.",
  "Strive higher.",
  "Grow stronger.",
];
